In [2]:
import torch 

In [10]:
#Generating tensors of our own 
a = torch.arange(0 , 10 , 2)
a
# for linear spaced tensor 
b = torch.linspace(1 , 9 , 550)
# if i want to create as the same shape of the b then i can do 
c = torch.empty_like(b)
d = torch.zeros_like(b)
e = torch.ones_like(b)
d 
e 

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 

In [20]:
#matrix multiplication 
torch.matmul(c , d)
#dotproduct 
torch.dot(c,d)
#transpose 
#torch.transpose()
#determinant
# torch.det(x)
#for inversing
#torch.inverse()
#calculating the  .log .exp .sqrt


tensor(0.)

In [12]:
#if i have to make in one range of the tensor 
f = torch.tensor([1,2,3])
torch.clamp(f , min=2 , max=2)

tensor([2, 2, 2])

In [2]:
tensor_1d = torch.tensor([1,2,3])
print("1D Tensor (Vector):")
print(tensor_1d)
print()

1D Tensor (Vector):
tensor([1, 2, 3])



In [3]:
tensor_2d = torch.tensor([[1,2],[3,4]])
print("2D Tensor(Matrix)")
print(tensor_2d)
print()

2D Tensor(Matrix)
tensor([[1, 2],
        [3, 4]])



In [4]:
random_tensor = torch.rand(2 , 3)
print("Random Tensor(2*3):")
print(random_tensor)
print()

Random Tensor(2*3):
tensor([[0.6974, 0.1086, 0.1511],
        [0.6271, 0.9279, 0.3368]])



In [5]:
zeros_tensor = torch.zeros(2,3)
print("Zeros Tensor (2*3):")
print(zeros_tensor)
print()

Zeros Tensor (2*3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [6]:
ones_tensor = torch.ones(2,3)
print("Ones Tensor(2*3)")
print(ones_tensor)

Ones Tensor(2*3)
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
#Tensor Operations 
#Indexing 
# Multiple Indexing  operations are performed using pytorch which are inplace changes the values of tensors without making the copy that whereas out of place operations don't 
# index_add index_add_(dim,index , tensor)
# adding along 0th axis ->columns 
x = torch.zeros(5,5)
te = torch.tensor([[1,3,5,7,9] , [1, 3 , 5,7,9] ], dtype = torch.float32)
index0 = torch.tensor([0,4])
x.index_add_(0,index0, te)
print( x)
print(torch.sum(x))
print(torch.sum(x ,dim=1))



tensor([[1., 3., 5., 7., 9.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 3., 5., 7., 9.]])
tensor(50.)
tensor([25.,  0.,  0.,  0., 25.])


In [27]:
# Adding along 1st axis -> Rows
y = torch.zeros(2,4)
tn1 = torch.tensor([[1, 2 , 4,6] , [2, 3 , 4 ,5]] , dtype=torch.float32)
index1 = torch.tensor([0,1 ,2 ,1])
y.index_add_(1 , index1 , tn1)



tensor([[1., 8., 4., 0.],
        [2., 8., 4., 0.]])

tensor([[1., 2., 4., 6.],
        [2., 3., 4., 5.]])

In [13]:
#filling along the the indices 
c = torch.randn(4,4)
index = torch.tensor([0,2])
c.index_fill_(0,index,5)
c

tensor([[ 5.0000,  5.0000,  5.0000,  5.0000],
        [-2.1748,  1.0790, -0.4242,  0.9848],
        [ 5.0000,  5.0000,  5.0000,  5.0000],
        [-0.1760,  0.6366, -0.6098,  1.0706]])

tensor([[-1.1307, -0.1854, -0.4842, -0.3746, -1.8865],
        [-1.4561, -0.7364, -0.4265,  1.7076,  0.1194],
        [-1.0661,  0.8627, -1.4485, -0.1114,  0.1421],
        [-0.9745, -0.0385, -0.6884,  0.3616,  0.0521],
        [-0.6745, -0.3288, -0.8827,  0.4371,  0.3286]])
